import { exec as execChildProcess } from 'child_process';
import { promisify } from 'util';
import { promises as fs } from 'fs';
import { join, basename } from 'path';
import { v4 as uuid } from 'uuid';
import type { WorktreeInfo, GitStatus, GitFileStatus } from '@agentic-os/types';

const exec = promisify(execChildProcess);

export class WorktreeManager {
  private basePath: string;
  private mainBranch: string;

  constructor(basePath: string, mainBranch = 'main') {
    this.basePath = basePath;
    this.mainBranch = mainBranch;
  }

  /**
   * Initialize a new project repository
   */
  async initProjectRepo(projectId: string): Promise<string> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Create project directory
    await fs.mkdir(projectPath, { recursive: true });
    
    // Initialize git repo
    await this.exec('git init', projectPath);
    
    // Configure git user for commits
    await this.exec('git config user.email "agent@agentic-os.dev"', projectPath);
    await this.exec('git config user.name "Agentic OS"', projectPath);
    
    // Create main branch with initial structure
    await this.exec(`git checkout -b ${this.mainBranch}`, projectPath);
    
    // Create initial README
    await fs.writeFile(
      join(projectPath, 'README.md'),
      `# ${projectId}\n\nGenerated by Agentic OS\n`,
      'utf-8'
    );
    
    // Initial commit
    await this.exec('git add . && git commit -m "Initial structure"', projectPath);
    
    return projectPath;
  }

  /**
   * Create a new worktree for a task
   */
  async createWorktree(
    projectPath: string,
    taskId: string,
    parentBranch?: string
  ): Promise<WorktreeInfo> {
    const branchName = this.getBranchName(taskId);
    const worktreePath = join(
      this.basePath,
      'worktrees',
      `wt-${uuid().slice(0, 8)}`
    );
    
    // Ensure worktrees directory exists
    await fs.mkdir(join(this.basePath, 'worktrees'), { recursive: true });
    
    // Create branch from parent or main
    const baseBranch = parentBranch || this.mainBranch;
    
    // Check if branch exists in any existing worktree
    const rawResult = await this.exec('git branch -a', projectPath);
    const existingBranches = rawResult.stdout || rawResult;
    
    // List all existing worktrees to check if branch is in use
    const worktreesResult = await this.exec('git worktree list', projectPath);
    const existingWorktrees = worktreesResult.stdout || worktreesResult;
    
    // Check if branch is already used by any worktree
    const branchInUse = existingWorktrees.includes(branchName) || existingBranches.includes(branchName);
    
    if (branchInUse) {
      // Find the existing worktree path for this branch
      const lines = existingWorktrees.split('\n');
      let existingPath = null;
      for (const line of lines) {
        if (line.includes(branchName)) {
          // Extract path from line (format: "path HEAD commit message")
          existingPath = line.split(' ')[0];
          break;
        }
      }
      
      if (existingPath) {
        return {
          branch: branchName,
          path: existingPath,
          isMain: false,
        };
      }
      
      // If branch exists but no worktree, create worktree without branch flag
      await this.exec(
        `git worktree add ${worktreePath}`,
        projectPath
      );
    } else {
      // Create new branch and worktree
      await this.exec(
        `git worktree add -b ${branchName} ${worktreePath} ${baseBranch}`,
        projectPath
      );
    }
    
    // Configure git user in worktree
    await this.exec('git config user.email "agent@agentic-os.dev"', worktreePath);
    await this.exec('git config user.name "Agentic OS"', worktreePath);
    
    return {
      branch: branchName,
      path: worktreePath,
      isMain: false,
    };
  }

  /**
   * Merge a worktree branch back to main
   */
  async mergeWorktree(projectPath: string, branchName: string, message?: string): Promise<void> {
    // Checkout main branch
    await this.exec(`git checkout ${this.mainBranch}`, projectPath);
    
    // Merge the worktree branch
    const mergeMsg = message || `Merge ${branchName}`;
    try {
      await this.exec(
        `git merge ${branchName} --no-ff -m "${mergeMsg}"`,
        projectPath
      );
    } catch (error) {
      // Handle merge conflicts - rollback
      await this.exec(`git merge --abort`, projectPath);
      throw new Error(`Merge conflict in branch ${branchName}`);
    }
  }

  /**
   * Delete a worktree
   */
  async deleteWorktree(projectPath: string, worktreePath: string, force = false): Promise<void> {
    const flag = force ? '--force' : '';
    await this.exec(`git worktree remove ${worktreePath} ${flag}`, projectPath);
  }

  /**
   * Get list of all worktrees for a project
   */
  async listWorktrees(projectPath: string): Promise<WorktreeInfo[]> {
    const { stdout } = await this.exec('git worktree list --porcelain', projectPath);
    
    const worktrees: WorktreeInfo[] = [];
    const entries = stdout.split('\n\n').filter(Boolean);
    
    for (const entry of entries) {
      const lines = entry.split('\n');
      const worktreePath = lines.find(l => l.startsWith('worktree '))?.slice(9) || '';
      const branch = lines.find(l => l.startsWith('branch '))?.slice(7) || '';
      const head = lines.find(l => l.startsWith('HEAD '))?.slice(4) || '';
      
      if (worktreePath) {
        worktrees.push({
          branch: branch || head,
          path: worktreePath,
          isMain: branch.includes(this.mainBranch) || head === this.mainBranch,
        });
      }
    }
    
    return worktrees;
  }

  /**
   * Get git status for a worktree
   */
  async getStatus(worktreePath: string): Promise<GitStatus> {
    const { stdout: branch } = await this.exec(
      'git branch --show-current',
      worktreePath
    );
    
    const { stdout: status } = await this.exec(
      'git status --porcelain',
      worktreePath
    );
    
    const { stdout: aheadBehind } = await this.exec(
      'git rev-list --left-right --count HEAD...origin/HEAD',
      worktreePath
    ).catch(() => ({ stdout: '0 0' }));
    
    const [ahead, behind] = aheadBehind.trim().split(/\s+/).map(Number);
    
    const files: GitFileStatus[] = status
      .split('\n')
      .filter(line => line.trim())
      .map(line => {
        const indexStatus = line[0];
        const workTreeStatus = line[1];
        const path = line.slice(3);
        
        // Determine effective status (prefer more significant status)
        let effectiveStatus: GitFileStatus['status'] = '?';
        if (indexStatus === '?' && workTreeStatus === '?') {
          effectiveStatus = '?';
        } else if (indexStatus === 'D' || workTreeStatus === 'D') {
          effectiveStatus = 'D';
        } else if (indexStatus === 'R') {
          effectiveStatus = 'R';
        } else if (indexStatus === 'A') {
          effectiveStatus = 'A';
        } else if (indexStatus !== ' ' && indexStatus !== '?') {
          effectiveStatus = 'M';
        } else if (workTreeStatus !== ' ') {
          effectiveStatus = 'M';
        } else {
          effectiveStatus = '?';
        }
        
        return {
          path,
          status: effectiveStatus,
          staged: indexStatus !== ' ' && indexStatus !== '?',
        };
      });
    
    return {
      branch: branch.trim(),
      ahead: isNaN(ahead) ? 0 : ahead,
      behind: isNaN(behind) ? 0 : behind,
      files,
    };
  }

  /**
   * Stage files for commit
   */
  async stageFiles(worktreePath: string, patterns: string[]): Promise<void> {
    for (const pattern of patterns) {
      await this.exec(`git add ${pattern}`, worktreePath);
    }
  }

  /**
   * Create a commit
   */
  async commit(worktreePath: string, message: string): Promise<string> {
    const { stdout } = await this.exec(
      `git commit -m "${message.replace(/"/g, '\\"')}"`,
      worktreePath
    );
    
    // Extract commit hash
    const match = stdout.match(/([a-f0-9]{40})/);
    return match ? match[1] : '';
  }

  /**
   * Get diff between worktree and main
   */
  async getDiff(worktreePath: string, filePath?: string): Promise<string> {
    const fileFlag = filePath ? `-- ${filePath}` : '';
    const { stdout } = await this.exec(
      `git diff ${this.mainBranch}...HEAD ${fileFlag}`,
      worktreePath
    );
    return stdout;
  }

  /**
   * Generate a deterministic branch name from task ID
   */
  getBranchName(taskId: string): string {
    // Create a short, URL-safe hash from UUID
    const clean = taskId.replace(/-/g, '').slice(0, 8);
    return `task/${clean}`;
  }

  /**
   * Get the main project path from a worktree path
   */
  async getMainProjectPath(worktreePath: string): Promise<string> {
    // Navigate up to find the git repo root
    let current = worktreePath;
    let parent = basename(current);
    
    while (parent !== 'worktrees' && current !== this.basePath) {
      const gitDir = join(current, '.git');
      try {
        await fs.access(gitDir);
        // Found the git root
        return current;
      } catch {
        // Not here, go up
        current = join(current, '..');
        parent = basename(current);
      }
    }
    
    // Fallback: use base path
    return join(this.basePath, '..');
  }

  /**
   * Check if a worktree has uncommitted changes
   */
  async hasUncommittedChanges(worktreePath: string): Promise<boolean> {
    const { stdout } = await this.exec('git status --porcelain', worktreePath);
    return stdout.trim().length > 0;
  }

  /**
   * Stash changes before switching
   */
  async stash(worktreePath: string, message?: string): Promise<void> {
    const stashMsg = message || `WIP before ${this.getBranchName(uuid())}`;
    await this.exec(`git stash push -m "${stashMsg}"`, worktreePath);
  }

  /**
   * Apply stashed changes
   */
  async applyStash(worktreePath: string, stashId = 'stash@{0}'): Promise<void> {
    await this.exec(`git stash pop ${stashId}`, worktreePath);
  }

  // ============================================
  // Branch Management
  // ============================================

  /**
   * List all branches in the project
   */
  async listBranches(projectId: string): Promise<Array<{
    name: string;
    current: boolean;
    ahead: number;
    behind: number;
  }>> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Get local branches
    const { stdout: localBranches } = await this.exec(
      'git for-each-ref --format="%(refname:short)|%(HEAD)" refs/heads/',
      projectPath
    );
    
    // Get remote branches
    const { stdout: remoteBranches } = await this.exec(
      'git for-each-ref --format="%(refname:short)" refs/remotes/',
      projectPath
    ).catch(() => ({ stdout: '' }));
    
    const branches: Array<{
      name: string;
      current: boolean;
      ahead: number;
      behind: number;
    }> = [];
    
    // Parse local branches
    for (const line of (localBranches || '').split('\n').filter(Boolean)) {
      const [name, head] = line.split('|');
      branches.push({
        name: name.trim(),
        current: head?.trim() === '*',
        ahead: 0,
        behind: 0,
      });
    }
    
    return branches;
  }

  /**
   * Get current branch name
   */
  async getCurrentBranch(projectId: string): Promise<string> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    const { stdout } = await this.exec(
      'git branch --show-current',
      projectPath
    );
    return stdout.trim();
  }

  /**
   * Create a new branch
   */
  async createBranch(
    projectId: string,
    branchName: string,
    baseBranch: string = 'main'
  ): Promise<{ branchName: string; worktreePath: string }> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    const worktreePath = join(
      this.basePath,
      'worktrees',
      `wt-${uuid().slice(0, 8)}`
    );
    
    // Ensure worktrees directory exists
    await fs.mkdir(join(this.basePath, 'worktrees'), { recursive: true });
    
    // Create branch and worktree
    await this.exec(
      `git worktree add -b ${branchName} ${worktreePath} ${baseBranch}`,
      projectPath
    );
    
    // Configure git user
    await this.exec('git config user.email "agent@agentic-os.dev"', worktreePath);
    await this.exec('git config user.name "Agentic OS"', worktreePath);
    
    return { branchName, worktreePath };
  }

  /**
   * Switch to a branch
   */
  async switchBranch(projectId: string, branchName: string): Promise<void> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Check if branch has a worktree
    const worktrees = await this.listWorktrees(projectPath);
    const existing = worktrees.find(w => 
      w.branch.includes(branchName) || w.branch === branchName
    );
    
    if (existing) {
      throw new Error(`Branch ${branchName} is checked out in another worktree at ${existing.path}`);
    }
    
    await this.exec(`git checkout ${branchName}`, projectPath);
  }

  /**
   * Delete a branch
   */
  async deleteBranch(projectId: string, branchName: string): Promise<void> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Find and remove any worktrees for this branch
    const worktrees = await this.listWorktrees(projectPath);
    const existing = worktrees.find(w => 
      w.branch.includes(branchName) || w.branch === branchName
    );
    
    if (existing) {
      await this.deleteWorktree(projectPath, existing.path, true);
    }
    
    // Delete the branch
    await this.exec(`git branch -D ${branchName}`, projectPath);
  }

  /**
   * Get branch status (ahead/behind)
   */
  async getBranchStatus(
    projectId: string,
    branchName: string
  ): Promise<{ ahead: number; behind: number; commits: string[] }> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Get commits ahead of main
    const { stdout: commits } = await this.exec(
      `git log ${this.mainBranch}..${branchName} --oneline`,
      projectPath
    ).catch(() => ({ stdout: '' }));
    
    // Count ahead/behind
    const ahead = commits.split('\n').filter(Boolean).length;
    
    return {
      ahead,
      behind: 0,
      commits: commits.split('\n').filter(Boolean),
    };
  }

  /**
   * Get changed files between branches
   */
  async getChangedFiles(
    projectId: string,
    branchName: string,
    baseBranch: string = 'main'
  ): Promise<Array<{
    path: string;
    status: string;
  }>> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    const { stdout } = await this.exec(
      `git diff --name-status ${baseBranch}...${branchName}`,
      projectPath
    );
    
    return stdout
      .split('\n')
      .filter(Boolean)
      .map(line => {
        const [status, ...pathParts] = line.split('\t');
        return {
          status: status as string,
          path: pathParts.join('\t'),
        };
      });
  }

  /**
   * Compare two branches
   */
  async compareBranches(
    projectId: string,
    fromBranch: string,
    toBranch: string
  ): Promise<{
    added: string[];
    removed: string[];
    modified: string[];
    stats: { additions: number; deletions: number };
  }> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Get all changes
    const { stdout: diff } = await this.exec(
      `git diff --name-status ${fromBranch}...${toBranch}`,
      projectPath
    );
    
    const added: string[] = [];
    const removed: string[] = [];
    const modified: string[] = [];
    
    for (const line of diff.split('\n').filter(Boolean)) {
      const [status, ...pathParts] = line.split('\t');
      const path = pathParts.join('\t');
      
      switch (status) {
        case 'A': added.push(path); break;
        case 'D': removed.push(path); break;
        case 'M': modified.push(path); break;
      }
    }
    
    // Get line stats
    const { stdout: stats } = await this.exec(
      `git diff --stat ${fromBranch}...${toBranch}`,
      projectPath
    );
    
    // Parse stats line (e.g., "5 files changed, 20 insertions(+), 5 deletions(-)")
    const insertions = (stats.match(/(\d+) insertion/i)?.[1] || '0');
    const deletions = (stats.match(/(\d+) deletion/i)?.[1] || '0');
    
    return {
      added,
      removed,
      modified,
      stats: {
        additions: parseInt(insertions),
        deletions: parseInt(deletions),
      },
    };
  }

  /**
   * Merge a branch into another
   */
  async mergeBranch(
    projectId: string,
    sourceBranch: string,
    targetBranch: string = 'main'
  ): Promise<{ success: boolean; conflicts?: string[] }> {
    const projectPath = join(this.basePath, `project-${projectId}`);
    
    // Checkout target branch
    await this.exec(`git checkout ${targetBranch}`, projectPath);
    
    try {
      // Attempt merge
      const result = await this.exec(
        `git merge ${sourceBranch} --no-ff -m "Merge ${sourceBranch} into ${targetBranch}"`,
        projectPath
      );
      
      return { success: true };
    } catch (error: any) {
      // Check for conflicts
      const { stdout: conflictedFiles } = await this.exec(
        'git diff --name-only --diff-filter=U',
        projectPath
      );
      
      return {
        success: false,
        conflicts: conflictedFiles.split('\n').filter(Boolean),
      };
    }
  }

  // ============================================
  // Private Helpers
  // ============================================

  private exec(command: string, cwd: string): Promise<{ stdout: string; stderr: string }> {
    return new Promise((resolve, reject) => {
      exec(command, { cwd, timeout: 30000 }, (error, stdout, stderr) => {
        if (error) {
          reject(new Error(`Git command failed: ${command}\n${error.message}`));
        } else {
          resolve({ stdout, stderr });
        }
      });
    });
  }
}
